// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCap2bNEsqKMs_lcPusTSxOsbTANYiEskM',
    appId: '1:826261927367:web:8330d9ba386143fb4c95e2',
    messagingSenderId: '826261927367',
    projectId: 'humanposeestimation-de972',
    authDomain: 'humanposeestimation-de972.firebaseapp.com',
    storageBucket: 'humanposeestimation-de972.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwOQ0lU_WsdgR5s5D853cGmZI9PdPeFLc',
    appId: '1:826261927367:android:1f889303bbec16144c95e2',
    messagingSenderId: '826261927367',
    projectId: 'humanposeestimation-de972',
    storageBucket: 'humanposeestimation-de972.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Ql1-8rpgSuvEPfyQIAiTN9KjOYyiquo',
    appId: '1:826261927367:ios:5672515b3fba68b94c95e2',
    messagingSenderId: '826261927367',
    projectId: 'humanposeestimation-de972',
    storageBucket: 'humanposeestimation-de972.firebasestorage.app',
    iosClientId: '826261927367-mn1o7tg6v8aq2e5utdh16vcbcka8nlck.apps.googleusercontent.com',
    iosBundleId: 'com.bpt.bpt',
  );
}
